//! The `write_file` tool. Split out of `fs`; logic unchanged.

use anyhow::{anyhow, Context, Result};
use async_trait::async_trait;
use serde::Deserialize;
use serde_json::{json, Value};

use crate::tools::{BuiltinTool, ToolContext, UndoEntry};

use super::common::{
    atomic_write_preserving_permissions, ensure_not_stale, rand_suffix, resolve, snapshot_meta,
};

pub struct WriteFile;

#[derive(Deserialize)]
struct WriteArgs {
    #[serde(alias = "file_path", alias = "filePath")]
    path: String,
    #[serde(alias = "contents", alias = "text")]
    content: String,
}

#[async_trait]
impl BuiltinTool for WriteFile {
    fn name(&self) -> &'static str {
        "write_file"
    }
    fn description(&self) -> &'static str {
        "Create a new file, or completely overwrite an existing one, with the supplied content. Parent directories are created automatically.\n\
\n\
When to use:\n\
- Creating brand-new files.\n\
- Truly replacing the entire contents of a file (e.g. regenerating an autogenerated artifact).\n\
\n\
When NOT to use:\n\
- DO NOT use this to modify an existing file. Use `edit_file` (for one change) or `multi_edit` (for several) so you don't silently destroy unrelated code.\n\
- Don't use this to append; read + edit_file, or read + write_file with the combined content.\n\
\n\
Safety: overwriting an EXISTING file is refused unless you read it first this session (new files need no read), so you can't discard content you never saw.\n\
\n\
Common mistakes:\n\
- Treating this as a faster alternative to `edit_file` — it isn't; it's a complete overwrite.\n\
- Leaving out trailing newlines or shebangs that the original file had.\n\
\n\
Parameters:\n\
- `path`: Relative path inside the working directory.\n\
- `content`: Exact bytes to write."
    }
    fn parameters_schema(&self) -> Value {
        json!({
            "type": "object",
            "properties": {
                "path": {"type": "string", "description": "Relative path inside the working directory."},
                "content": {"type": "string", "description": "Exact bytes to write."}
            },
            "required": ["path", "content"],
            "additionalProperties": false
        })
    }
    async fn compute_preview(&self, args: &Value, ctx: &ToolContext) -> Option<String> {
        let a: WriteArgs = serde_json::from_value(args.clone()).ok()?;
        let path = resolve(&ctx.cwd, &a.path).ok()?;
        let existing = tokio::fs::metadata(&path).await.ok().map(|m| m.len());
        Some(match existing {
            Some(n) => format!(
                "Overwrite {} ({n} bytes -> {} bytes)",
                a.path,
                a.content.len()
            ),
            None => format!("Create new file {} ({} bytes)", a.path, a.content.len()),
        })
    }
    async fn execute(&self, args: Value, ctx: &ToolContext) -> Result<String> {
        let a: WriteArgs = crate::tools::parse_args("write_file", args)?;
        let path = resolve(&ctx.cwd, &a.path)?;
        let existing_meta = match tokio::fs::metadata(&path).await {
            Ok(meta) => Some(meta),
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => None,
            Err(e) => return Err(e).with_context(|| format!("stat {}", path.display())),
        };
        if existing_meta.as_ref().is_some_and(|meta| meta.is_dir()) {
            return Err(anyhow!(
                "cannot write file over directory {}",
                path.display()
            ));
        }
        // Read-before-overwrite safety: refuse to replace an EXISTING file the
        // model hasn't read this session, so it can't silently discard content
        // it never saw. Creating a new file (no existing_meta) needs no read.
        if existing_meta.is_some() {
            let session = ctx.session.lock().await;
            if !session.read_files.contains(&path) {
                return Err(anyhow!(
                    "write_file refuses to overwrite {} because it was not read this session. \
                     Call read_file on it first so you don't discard unseen content (or use edit_file for a targeted change).",
                    path.display()
                ));
            }
            ensure_not_stale(&session, &path, "write_file")?;
        }
        // Snapshot prior contents as RAW BYTES, not UTF-8: a binary file that
        // exists must be restorable on undo. If an existing file cannot be
        // read, fail before overwriting — otherwise undo would treat it as a
        // newly-created file and delete it.
        let original = if existing_meta.is_some() {
            Some(
                tokio::fs::read(&path)
                    .await
                    .with_context(|| format!("read original {}", path.display()))?,
            )
        } else {
            None
        };
        if let Some(parent) = path.parent() {
            tokio::fs::create_dir_all(parent)
                .await
                .with_context(|| format!("create parent dirs for {}", parent.display()))?;
        }
        let tmp = path.with_extension(format!("write-{}.tmp", rand_suffix()));
        atomic_write_preserving_permissions(&path, &tmp, a.content.as_bytes()).await?;
        let (post_edit_mtime, post_edit_size) = snapshot_meta(&path);
        {
            // A freshly written file counts as "read" so a follow-up edit_file
            // doesn't spuriously demand a read_file of bytes the model just
            // authored. Refresh the (mtime, size) snapshot to the bytes we just
            // wrote so the staleness guard doesn't fire on the model's own
            // write. Same lock also records undo.
            let mut session = ctx.session.lock().await;
            session.read_files.insert(path.clone());
            session
                .read_file_meta
                .insert(path.clone(), (post_edit_mtime, post_edit_size));
            session.push_undo_entry(UndoEntry {
                path: path.clone(),
                original_content: original,
                post_edit_mtime,
                post_edit_size,
            });
        }
        Ok(format!(
            "Wrote {} bytes to {}",
            a.content.len(),
            path.display()
        ))
    }
}
