pub mod agent;
pub mod anthropic;
pub mod auth;
pub mod catalog;
pub mod client;
pub mod command;
pub mod config;
pub mod conscience;
pub mod context_report;
pub mod decisions;
pub mod doctor;
pub mod fallback;
pub mod handoff;
pub mod hooks;
pub mod mcp;
pub mod memory;
pub mod openai;
pub mod permissions;
pub mod pricing;
pub mod proof;
pub mod provider;
pub mod race;
pub mod repo_twin;
mod retry;
pub mod rounds;
pub mod seal;
pub mod secret_env;
mod sensitive;
pub mod session;
pub mod setup;
pub mod skill;
pub mod subagent;
mod tool_args;
pub mod tools;
pub mod usage;

#[cfg(test)]
mod reasoning_wire_tests;

pub use anyhow::{Error, Result};
